post/urls.py
#Library Import
from django.urls import path
#Local Import
from . import views


app_name='posts'
urlpatterns = [
    path('navbar/', views.Navbar.as_view(), name='navbar'),
    path('', views.HomeView.as_view(), name='home'),
    path("detail-post/<slug:slug>/", views.DetailPostView.as_view(), name="post_detail"),
    path("post-list/", views.PostListView.as_view(), name="post-list"),
    path('category/<slug:slug>', views.CategoryDetailView.as_view(), name="category_detail"),
    path('about-us/', views.AboutUsView.as_view(), name="about-us"),
    path('contact-us/', views.ContactUsView.as_view(), name="contact-us"),
]

rahnama/urls.py
#Library Import
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.utils.translation import gettext_lazy as _
#Local Import
from post.views import change_lang


urlpatterns = [
    path('change_lang', change_lang, name="change_lang"),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('post.urls', namespace='posts')),
    prefix_default_language=False,
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{ message.tags }} text-center" style="color:black" {% endif %}>{{ message }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<header class="style2">
    <div class="container ">
        <div class="logo sec-title-inner2"><h3><a href="{% url 'posts:home' %}"><img src="{% static 'assets/images/logorahnama.jpg' %}" style="width:170px"/></a></h3></div>
        <nav class="">
            <div>
            <a class="thm-btn brd-rd5" href="{% url 'posts:contact-us' %}" title="">{% trans "تماس با ما" %}</a>
                <ul>
                    <li><a href="{% url 'posts:home' %}">{% trans "خانه" %}</a></li>
                    <li><a href="{% url 'posts:post-list' %}">{% trans "اخبار" %}</a></li>
                    {% for category in categories %}
                        <li {% if category.children.all %}class="menu-item-has-children"{% endif %}><a href="{{category.get_absolute_url}}" title="">{{category.title}}</a>
                            <ul>
                                {% for category in category.children.all %}
                                <li><a href="{{category.get_absolute_url}}" title="">{{category.title}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}

                    <li><a href="{% url 'posts:about-us' %}">{% trans "درباره ما" %}</a></li>
                    <li>
                    {% if LANGUAGE_CODE == 'en' %}
                        <a href="/">فارسی</a>
                    {% endif %}
                    {% if LANGUAGE_CODE == 'fa' %}
                        <a href="{% url 'change_lang' %}?lang=en&next=/en">EN</a>
                    {% endif %}
                    </li>
                    
                    <li></li>
                </ul>
            </div>
        </nav>
    </div>
</header><!-- Header -->

<div class="rspn-hdr">
    <div class="rspn-mdbr">
    </div>
    <div class="lg-mn">
        <div class="logo sec-title-inner2"><h3><a href="{% url 'posts:home' %}"><img src="{% static 'assets/images/logorahnama.jpg' %}" style="width:100px" /></a></h3></div>
        <div class="rspn-cnt">

            {% comment %} {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                    {{ language.name_local }} ({{ language.code }})
                </option>
            {% endfor %} {% endcomment %}

            {% if LANGUAGE_CODE == 'en' %}
                <a href="{% url 'posts:home' %}">فارسی</a>
            {% endif %}
            {% if LANGUAGE_CODE == 'fa' %}
                <a href="{% url 'change_lang' %}?lang=en&next=/en">EN</a>
            {% endif %}

        </div>
        <span class="rspn-mnu-btn"> <i class="fa fa-list-ul"></i> </span>
    </div>
    <div class="rsnp-mnu">
        <span class="rspn-mnu-cls"> <i class="fa fa-times"></i> </span>
        <ul>
            <li><a href="{% url 'posts:home' %}">{% trans "خانه" %}</a></li>
            <li><a href="{% url 'posts:post-list' %}">{% trans "اخبار" %}</a></li>

            {% for category in categories %}
                <li class="menu-item-has-children"><a href="{{category.get_absolute_url}}" title="">{{category.title}}</a>
                    <ul>
                        {% for category in category.children.all %}
                        <li><a href="{{category.get_absolute_url}}" title="">{{category.title}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
            <li><a href="{% url 'posts:about-us' %}">{% trans "درباره ما" %}</a></li>
            <li><a href="{% url 'posts:contact-us' %}">{% trans "تماس با ما" %}</a></li>
        </ul>
    </div><!-- Responsive Menu -->
</div><!-- Responsive Header -->


<style>

.lg-mn {background-color: white;}
.lg-mn span {color:black;}

</style>